version: '3.8'

services:
  backend:
    build:
      context: ./JocaS2
    ports:
      - "25000:25000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./Front-end
    ports:
      - "8080:8080"
    depends_on:
      - backend
